name: CLI CI

on:
  push:
    paths: "cli/**"
    branches:
      - master
  pull_request:
    paths: "cli/**"

jobs:
  test:
    name: "Build & Test"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: cli
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Setup GCP credentials
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "290.0.1"
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: "Build"
        run: make build-all
      - name: "Validate"
        run: make validate
      - name: "Test"
        run: make test
