name: Python CI

on:
  push:
    paths: "python/**"
    branches:
    - master
  pull_request:
    paths: "python/**"

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: python
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Setup GCP credentials
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - name: Install tox
      run: pip install tox
    - name: Lint and test
      run: tox -e lint,py
